### ISSUE TITLE
Enhancements for the dashboard

### ISSUE THREAD

**Issue by Aerics84** [The-International-Screeps-Bot/Screeps-Grafana#1]
**Enhancements**
- Global Power Level & PGL Progress = accept 0
- Writing always Cpu or CPU

**Bugs**
- rc (remote count) not working. I have one remote room which shows on map visuals, but in memory it`s 0.
- eob (Energy output - Build) not working. Its always 0.
- ServerStats on mmo are all empty.

**Comment by pieterbrandsen** [comment]
1. Done
2. Done

1. No clue, then the bot itself doesnt work as expected
2. Remote build doesnt work because no construction happening but inside commune rooms it does count
3. Correct, I dont have access to mmo server stats so run with `npm run start-mmo`

Fix in commit https://github.com/The-International-Screeps-Bot/Screeps-Grafana/commit/5422d4265a170280fa2f8d73a567004e65299717
